apiVersion: apps/v1
kind: Deployment
metadata:
  name: vidly-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vidly-backend
  template:
    metadata:
      labels:
        app: vidly-backend
    spec:
      containers:
      - name: vidly-backend
        image: hanyhm1234/vidly-backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: DB_URL
          value: "mongodb://mongodb-service:27017/vidly"
---
apiVersion: v1
kind: Service
metadata:
  name: vidly-backend
spec:
  selector:
    app: vidly-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001